# Generated by Django 4.0.3 on 2022-04-02 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tag_alter_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='emial',
            new_name='email',
        ),
    ]
